server:
    port: 8080
spring:
    datasource:
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        generate-ddl: true

spring-doc:
    swagger-ui:
        path: /swagger-ui.html